name: FIT4110 Lab03 - Local
values:
  - key: env
    value: local
  - key: baseUrl
    value: 'http://localhost:8000'
  - key: authToken
    value: local-dev-token
  - key: teamName
    value: team-iot
  - key: aiVisionMockUrl
    value: 'http://localhost:4011'
  - key: tracePrefix
    value: fit4110-lab03
