name: FIT4110 Lab03 - Mock
values:
  - key: env
    value: mock
  - key: baseUrl
    value: 'http://localhost:4010'
  - key: authToken
    value: lab-token
  - key: teamName
    value: team-iot
  - key: aiVisionMockUrl
    value: 'http://localhost:4011'
  - key: tracePrefix
    value: fit4110-lab03
